export const REQUEST_ANIMAL = 'REQUEST_ANIMAL'
export const ERROR_ANIMAL = 'ERROR_ANIMAL'

export const FETCH_ANIMAL_SUCCESS = 'FETCH_ANIMAL_SUCCESS'
export const ADD_ANIMAL_SUCCESS = 'ADD_ANIMAL_SUCCESS'
export const DELETE_ANIMAL_SUCCESS = 'DELETE_ANIMAL_SUCCESS'
export const EDIT_ANIMAL_SUCCESS = 'EDIT_ANIMAL_SUCCESS'

export const FETCH_REQUEST_ANIMAL_LIST = 'FETCH_REQUEST_ANIMAL_LIST'
export const FETCH_SUCCESS_ANIMAL_LIST = 'FETCH_SUCCESS_ANIMAL_LIST'
export const FILTER_LIST_SUCCESS = 'FILTER_LIST_SUCCESS'
export const FETCH_ERROR_ANIMAL_LIST = 'FETCH_ERROR_ANIMAL_LIST'

export const REQUEST_USER = 'REQUEST_USER'
export const FETCH_SUCCESS_USER = 'FETCH_SUCCESS_USER'
export const USER_ERROR = 'USER_ERROR'

export const FETCH_REQUEST_USERS_ANIMALS = 'FETCH_REQUEST_USERS_ANIMALS'
export const FETCH_SUCCESS_USERS_ANIMALS = 'FETCH_SUCCESS_USERS_ANIMALS'
export const FETCH_ERROR_USERS_ANIMALS = 'FETCH_ERROR_USERS_ANIMALS'

export const FETCH_REQUEST_LOGIN = 'FETCH_REQUEST_LOGIN'
export const FETCH_SUCCESS_LOGIN = 'FETCH_SUCCESS_LOGIN'
export const FETCH_ERROR_LOGIN = 'FETCH_ERROR_LOGIN'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'

export const RECOVER_SUCCESS = 'RECOVER_SUCCESS'
export const RECOVER_ERROR = 'RECOVER_ERROR'

export const DELETE_SUCCESS = 'DELETE_SUCCESS'
export const EDIT_SUCCESS = 'EDIT_SUCCESS'
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCCESS'

export const RESET = 'RESET'
